apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kmleungdevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kmleungdevops
    spec:
      containers:
      - name: kmleungdevops
        image: michaelacr.azurecr.io/leungkimming/devopstrain:$BUILD_ID
        ports:
        - containerPort: 4585
---
apiVersion: v1
kind: Service
metadata:
  name: kmleungdevops
spec:
  type: LoadBalancer
  ports:
  - port: 14585
  selector:
    app: kmleungdevops
