apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: michaeldevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: michaeldevops
    spec:
      containers:
      - name: michaeldevops
        image: docker.io/pleungdev/michaeldevops:$BUILD_ID
        ports:
        - containerPort: 4585
---
apiVersion: v1
kind: Service
metadata:
  name: michaeldevops
spec:
  type: LoadBalancer
  ports:
  - port: 4585
  selector:
    app: michaeldevops
